:Author: yahyafakrhoji
:Email: yahya.fakhroji@gmail.com
:Date: 10/10/2017
:Revision: version#
:License: Public Domain

= Automatic Garden Watering Smart System

Describe your project

== Step 1: Installation
Please describe the steps to install this project.

For example:

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png attached to the sketch

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact yahyafakrhoji <yahya.fakhroji@gmail.com> or <akbarsaputrait@outlook.com>

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name         | Part number | Quantity
| 1 | Jumper Cabel       | -           | 10       
| 2 | Water Pump         | 12 Volt     | 5        
| 3 | Arduino Uno        | -           | 1        
| 4 | Bluetooth          | HC-05       | 1        
| 5 | Breadboard         | -           | 1        
| 6 | Relay              | 220v        | 1        
| 7 | LCD Display        | 16 x 2      | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
